apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2024-02-29T13:58:27Z"
  generation: 10
  labels:
    app: tic-tac-toe
  name: tic-tac-toe
  namespace: gruppe-gaming
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tic-tac-toe
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tic-tac-toe
    spec:
      containers:
      - image: ghcr.io/ci-cd-2024-dhbw-hdh/gruppe-gaming:main
        imagePullPolicy: IfNotPresent
        name: gruppe-gaming
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30