apiVersion: v1
kind: Service
metadata:
  labels:
    app: tic-tac-toe
  name: tic-tac-toe
  namespace: default
spec:
  clusterIP: 10.245.231.47
  clusterIPs:
  - 10.245.231.47
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-80
    nodePort: 32689
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: tic-tac-toe
  sessionAffinity: None
  type: NodePort