on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy
        run: |
          kubectl apply -f .kubernetes/deployment.yaml
          kubectl apply -f .kubernetes/service.yaml
      - name: Set imagePullSecret
        uses: azure/k8s-create-secret@v4
        with:
          namespace: 'gruppe-gaming'
          secret-name: 'regcred'
          container-registry-url: 'ghcr.io'
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        id: create-secret